FROM node:12-buster-slim

# ARG USER=docker
# ARG GID=0
# ARG UID=0

# RUN useradd -ms /bin/bash $USER
# USER $USER
# RUN echo "The user is: " $USER
# RUN touch ~/.profile
# RUN . ~/.profile
# RUN . ~/.bashrc

